---
- name: Deploy Cacti on Linux servers
  become: yes
  hosts: linuxServers
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create Docker Compose directory
      file:
        path: /opt/cacti
        state: directory
        mode: '0755'

    - name: Create Docker Compose file
      copy:
        dest: /opt/cacti/docker-compose.yml
        content: |
          version: '3.8'
          services:
            db:
              image: million12/mariadb
              container_name: db
              environment:
                MARIADB_USER: xiam
                MARIADB_PASS: Xi@m2007!
              volumes:
                - db_data:/var/lib/mysql
            cacti:
              image: polinux/cacti
              depends_on:
                - db
              ports:
                - "80:80"
                - "81:81"
                - "443:443"
              environment:
                DB_USER: xiam
                DB_PASS: Xi@m2007!
                DB_ADDRESS: db
          volumes:
            db_data:

    - name: Start Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/cacti
