---
- name: Deploy Cacti on Linux servers
  become: yes
  hosts: linuxServers
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull MariaDB image
      docker_image:
        name: million12/mariadb
        source: pull

    - name: Pull Cacti image
      docker_image:
        name: polinux/cacti
        source: pull

    - name: Create Cacti database container
      docker_container:
        name: cacti-db
        image: million12/mariadb
        state: started
        restart_policy: always
        environment:
          MARIADB_USER: xiam
          MARIADB_PASS: Xi@m2007!

    - name: Create Cacti web application container
      docker_container:
        name: cacti-app
        image: polinux/cacti
        state: started
        restart_policy: always
        ports:
          - "80:80"
          - "443:443"
        environment:
          DB_USER: xiam
          DB_PASS: Xi@m2007!
          DB_ADDRESS: cacti-db
