---
- name: Playbook for linux server
  become: yes
  hosts: linuxServers
  tasks:

  - name: Install packages
    apt:
      update_cache: yes
      cache_valid_time: 3600
      pkg:
        - vim
        - ncdu
      state: present